export const users = [
  {
    _id: '63cbbe5af275fcd74422556c',
    index: 0,
    guid: 'c9ce5d34-0df0-4053-8dcf-9c5ccb4a8b41',
    isActive: true,
    balance: '$3,698.78',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'green',
    name: 'Bryan Sweet',
    gender: 'male',
    company: 'PLEXIA',
    email: 'bryansweet@plexia.com',
    phone: '+1 (997) 598-3131',
    address: '676 Goodwin Place, Alafaya, District Of Columbia, 2873',
    about:
      'Nostrud Lorem occaecat consectetur nostrud do eu officia veniam qui aute. Ullamco id cillum ipsum ut sit enim eiusmod in exercitation do tempor. Sint eu irure ea culpa excepteur labore ad. Eiusmod adipisicing tempor consectetur nulla.\r\n',
    registered: '2016-10-14T07:40:15 -03:00',
    latitude: 74.593802,
    longitude: 4.627139,
    tags: [
      'eiusmod',
      'qui',
      'sint',
      'officia',
      'cupidatat',
      'proident',
      'aute',
    ],
    friends: [
      {
        id: 0,
        name: 'Hutchinson Lowe',
      },
      {
        id: 1,
        name: 'Gallegos Chan',
      },
      {
        id: 2,
        name: 'Lois Levy',
      },
    ],
    greeting: 'Hello, Bryan Sweet! You have 3 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '63cbbe5aa8c087781cb68b68',
    index: 1,
    guid: '1e4345f9-c226-4e11-8480-b40f357d8a35',
    isActive: true,
    balance: '$1,776.30',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'blue',
    name: 'Mariana Cash',
    gender: 'female',
    company: 'GEEKNET',
    email: 'marianacash@geeknet.com',
    phone: '+1 (955) 411-3958',
    address: '829 Neptune Avenue, Blandburg, California, 2510',
    about:
      'Amet exercitation cillum amet officia esse pariatur sit dolor eiusmod veniam ipsum elit anim commodo. Incididunt eiusmod dolor ullamco ad qui enim duis elit dolore ullamco in eu. Non reprehenderit anim anim cillum do amet qui deserunt laborum minim anim. Magna exercitation officia sit aliquip occaecat. Pariatur ut voluptate non cupidatat nisi laborum consequat est labore ad deserunt occaecat enim ullamco.\r\n',
    registered: '2014-07-08T06:45:40 -03:00',
    latitude: 69.427736,
    longitude: 102.097112,
    tags: [
      'adipisicing',
      'deserunt',
      'incididunt',
      'amet',
      'irure',
      'cupidatat',
      'adipisicing',
    ],
    friends: [
      {
        id: 0,
        name: 'Deanne Love',
      },
      {
        id: 1,
        name: 'Arnold Preston',
      },
      {
        id: 2,
        name: 'Price Lynch',
      },
    ],
    greeting: 'Hello, Mariana Cash! You have 10 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '63cbbe5a9de0daf5d671ac43',
    index: 2,
    guid: '2ae4d755-5b01-4192-8b07-4d7b49fb852b',
    isActive: false,
    balance: '$2,661.72',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'green',
    name: 'Laurel Harper',
    gender: 'female',
    company: 'ENERSAVE',
    email: 'laurelharper@enersave.com',
    phone: '+1 (878) 445-3072',
    address: '378 Cleveland Street, Harviell, Oregon, 4244',
    about:
      'Ad tempor commodo aute officia. Aliqua deserunt reprehenderit id ullamco sint quis et. Ullamco nisi in enim id et mollit esse nostrud adipisicing tempor in ex. Deserunt laboris esse eu eu enim aliquip reprehenderit in enim pariatur. Consectetur sunt duis veniam cillum reprehenderit irure. Mollit ullamco labore fugiat magna laborum irure nostrud aliqua nulla ea exercitation eu sunt. Aliquip Lorem ipsum ea nostrud.\r\n',
    registered: '2014-04-06T05:50:30 -03:00',
    latitude: -76.888255,
    longitude: 27.711447,
    tags: [
      'occaecat',
      'occaecat',
      'magna',
      'pariatur',
      'est',
      'qui',
      'voluptate',
    ],
    friends: [
      {
        id: 0,
        name: 'Angelica Butler',
      },
      {
        id: 1,
        name: 'Twila Fuller',
      },
      {
        id: 2,
        name: 'Dina Rios',
      },
    ],
    greeting: 'Hello, Laurel Harper! You have 5 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '63cbbe5abe5d70ef2c5b73ca',
    index: 3,
    guid: '1f77e4f8-097f-4d9b-8b54-9450a85cc7f5',
    isActive: true,
    balance: '$3,957.67',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'blue',
    name: 'Jane Sharpe',
    gender: 'female',
    company: 'PIGZART',
    email: 'janesharpe@pigzart.com',
    phone: '+1 (871) 578-3615',
    address: '966 Dictum Court, Clara, Wisconsin, 3572',
    about:
      'Ut ea id dolor tempor voluptate pariatur anim officia ipsum exercitation. Nisi commodo sint excepteur duis. Eiusmod adipisicing eu dolor exercitation aute tempor eu adipisicing id consectetur aliquip sunt minim mollit. Cillum aliquip labore duis magna minim quis eu eiusmod eu aliquip.\r\n',
    registered: '2017-02-04T02:01:35 -02:00',
    latitude: 32.681986,
    longitude: -141.44868,
    tags: ['et', 'in', 'tempor', 'nulla', 'cillum', 'proident', 'eiusmod'],
    friends: [
      {
        id: 0,
        name: 'Lora Coffey',
      },
      {
        id: 1,
        name: 'Meadows Sherman',
      },
      {
        id: 2,
        name: 'Daugherty Weiss',
      },
    ],
    greeting: 'Hello, Jane Sharpe! You have 4 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '63cbbe5afd58370b3e61401e',
    index: 4,
    guid: '476f250a-4627-4afe-9f9e-b3402ddad19f',
    isActive: true,
    balance: '$2,404.29',
    picture: 'http://placehold.it/32x32',
    age: 22,
    eyeColor: 'brown',
    name: 'Amalia Herring',
    gender: 'female',
    company: 'QUAILCOM',
    email: 'amaliaherring@quailcom.com',
    phone: '+1 (818) 516-2361',
    address: '383 Lamont Court, Cascades, Kentucky, 566',
    about:
      'Veniam labore sunt irure velit laborum tempor eu. Commodo magna occaecat consectetur do nisi dolore mollit nostrud culpa. Non id eu magna commodo Lorem anim magna mollit sint. Pariatur velit anim sint anim deserunt cupidatat et eu exercitation duis ut qui deserunt. Est et incididunt ut amet nisi consequat aliqua excepteur velit anim magna. Enim qui irure dolore eiusmod in deserunt sint proident mollit proident ea.\r\n',
    registered: '2021-10-11T12:16:22 -03:00',
    latitude: -49.349178,
    longitude: -162.661604,
    tags: [
      'dolor',
      'occaecat',
      'in',
      'aliqua',
      'consectetur',
      'proident',
      'sit',
    ],
    friends: [
      {
        id: 0,
        name: 'Staci Finley',
      },
      {
        id: 1,
        name: 'Elsa Hart',
      },
      {
        id: 2,
        name: 'April Tucker',
      },
    ],
    greeting: 'Hello, Amalia Herring! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '63cbbe5a6d06bae31297fafa',
    index: 5,
    guid: '8546e009-fc01-4a14-bcc3-166cff4cdb33',
    isActive: false,
    balance: '$1,547.49',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'blue',
    name: 'Nichols Craft',
    gender: 'male',
    company: 'ROUGHIES',
    email: 'nicholscraft@roughies.com',
    phone: '+1 (815) 403-3590',
    address: '661 Brooklyn Avenue, Cumminsville, Oklahoma, 6010',
    about:
      'Eu do cupidatat commodo proident ullamco anim laboris. Est ex enim esse ut enim elit excepteur magna deserunt laborum ex reprehenderit. Aliquip aliqua ex labore Lorem sunt incididunt quis reprehenderit minim.\r\n',
    registered: '2020-07-07T10:22:48 -03:00',
    latitude: -19.191475,
    longitude: -71.658817,
    tags: ['veniam', 'velit', 'ullamco', 'nostrud', 'eu', 'laborum', 'est'],
    friends: [
      {
        id: 0,
        name: 'James Pierce',
      },
      {
        id: 1,
        name: 'Graham Medina',
      },
      {
        id: 2,
        name: 'Dee Hill',
      },
    ],
    greeting: 'Hello, Nichols Craft! You have 3 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '63cbbe5ac1145c566757933d',
    index: 6,
    guid: 'db7e05c0-8e59-4b06-a5e6-8adc0dd32d75',
    isActive: true,
    balance: '$3,875.73',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'blue',
    name: 'Sherrie Gilbert',
    gender: 'female',
    company: 'DEMINIMUM',
    email: 'sherriegilbert@deminimum.com',
    phone: '+1 (957) 408-3450',
    address: '921 Beaumont Street, Saranap, Louisiana, 6036',
    about:
      'Sint aute ullamco quis ea ut commodo non adipisicing est sint. Aliquip ut esse ad ex excepteur proident anim commodo ipsum anim anim fugiat eu elit. Eu magna ex sit officia commodo ex adipisicing. Do ea sit minim cillum veniam nisi nisi duis.\r\n',
    registered: '2017-06-14T09:06:17 -03:00',
    latitude: 74.787129,
    longitude: 31.002693,
    tags: [
      'pariatur',
      'deserunt',
      'enim',
      'elit',
      'fugiat',
      'fugiat',
      'commodo',
    ],
    friends: [
      {
        id: 0,
        name: 'Santiago Montoya',
      },
      {
        id: 1,
        name: 'Webster Baird',
      },
      {
        id: 2,
        name: 'Clarice Thomas',
      },
    ],
    greeting: 'Hello, Sherrie Gilbert! You have 8 unread messages.',
    favoriteFruit: 'strawberry',
  },
];
